######################################################################
# Automatically generated by qmake (3.0) ? 1 2 19:37:01 2016
######################################################################

CONFIG += c++11 console
QT += widgets
TEMPLATE = app
TARGET = app
INCLUDEPATH += .

# Input
SOURCES += main.cpp
